<?php

return [
    'categories' => [
        'Medicamentos',
        'Analgesicos',
        'Antibioticos',
        'Anti-inflamatorios',
        'Antigripais e resfriado',
        'Alergia e rinite',
        'Gastrintestinal',
        'Cardiovascular',
        'Diabetes',
        'Hipertensao',
        'Saude mental',
        'Vitaminas e suplementos',
        'Fitoterapia',
        'Dermatologia',
        'Dermocosmeticos',
        'Higiene pessoal',
        'Beleza',
        'Cabelos',
        'Higiene bucal',
        'Infantil',
        'Materno e bebe',
        'Saude sexual',
        'Primeiros socorros',
        'Curativos',
        'Protecao solar',
        'Equipamentos medicos',
        'Dispositivos medicos',
        'Ortopedia',
        'Mobilidade',
        'Ocular',
        'Otorrino',
        'Testes e diagnostico',
        'Nutricao esportiva',
        'Produtos naturais',
        'Fraldas e incontinencia',
        'Casa e bem-estar',
        'Outros',
    ],
];
